"""make role non-nullable

Revision ID: a50e9d73f891
Revises: 8f0dd71be4e5
Create Date: 2025-05-18 07:45:12.412616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a50e9d73f891'
down_revision: Union[str, None] = '8f0dd71be4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobapplication') as batch_op:
        batch_op.alter_column('role', 
                              existing_type=sa.String(),
                              nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobapplication') as batch_op:
        batch_op.alter_column('role', 
                              existing_type=sa.String(),
                              nullable=True)
    # ### end Alembic commands ###
